In [2]:
%pip install numpy sentence-transformers faiss-cpu rank-bm25 openai python-dotenv ragas datasets pandas

Requirement already satisfied: numpy in C:\Users\Lalith\anaconda3\Lib\site-packages (2.1.3)
Requirement already satisfied: sentence-transformers in C:\Users\Lalith\anaconda3\Lib\site-packages (6.0.1)
Requirement already satisfied: faiss-cpu in C:\Users\Lalith\anaconda3\Lib\site-packages (1.15.0)
Requirement already satisfied: rank-bm25 in C:\Users\Lalith\anaconda3\Lib\site-packages (0.2.2)
Requirement already satisfied: openai in C:\Users\Lalith\anaconda3\Lib\site-packages (2.38.0)
Requirement already satisfied: python-dotenv in C:\Users\Lalith\anaconda3\Lib\site-packages (1.1.0)
Requirement already satisfied: ragas in C:\Users\Lalith\anaconda3\Lib\site-packages (0.4.3)
Requirement already satisfied: datasets in C:\Users\Lalith\anaconda3\Lib\site-packages (5.0.1)
Requirement already satisfied: pandas in C:\Users\Lalith\anaconda3\Lib\site-packages (2.2.3)
Requirement already satisfied: transformers<6.0.0,>=5.0.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from sentence-transformers) (5.17.0)
Requirement already satisfied: tokenizers>=0.19 in C:\Users\Lalith\anaconda3\Lib\site-packages (from sentence-transformers) (0.23.2)
Requirement already satisfied: huggingface-hub<2.0.0,>=1.3.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from sentence-transformers) (1.18.0)
Requirement already satisfied: torch>=2.2 in C:\Users\Lalith\anaconda3\Lib\site-packages (from sentence-transformers) (2.14.0)
Requirement already satisfied: scikit-learn>=1.1.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from sentence-transformers) (1.15.3)
Requirement already satisfied: typing_extensions>=4.10.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: click>=8.4.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (2025.3.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in C:\Users\Lalith\anaconda3\Lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in C:\Users\Lalith\anaconda3\Lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\Lalith\anaconda3\Lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (6.0.2)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.25.1)
Requirement already satisfied: anyio in C:\Users\Lalith\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (4.7.0)
Requirement already satisfied: certifi in C:\Users\Lalith\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (2025.4.26)
Requirement already satisfied: httpcore==1.* in C:\Users\Lalith\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in C:\Users\Lalith\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (3.19)
Requirement already satisfied: h11>=0.16 in C:\Users\Lalith\anaconda3\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.16.0)
Requirement already satisfied: regex>=2025.10.22 in C:\Users\Lalith\anaconda3\Lib\site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (2026.9.10)
Requirement already satisfied: safetensors>=0.8.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (0.8.0)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (1.5.0)
Requirement already satisfied: rich>=13.8.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in C:\Users\Lalith\anaconda3\Lib\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.0.4)
Requirement already satisfied: distro<2,>=1.7.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from openai) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from openai) (0.14.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from openai) (2.10.3)
Requirement already satisfied: sniffio in C:\Users\Lalith\anaconda3\Lib\site-packages (from openai) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in C:\Users\Lalith\anaconda3\Lib\site-packages (from pydantic<3,>=1.9.0->openai) (2.27.1)
Requirement already satisfied: tiktoken in C:\Users\Lalith\anaconda3\Lib\site-packages (from ragas) (0.13.0)
Requirement already satisfied: nest-asyncio in C:\Users\Lalith\anaconda3\Lib\site-packages (from ragas) (1.6.0)
Requirement already satisfied: appdirs in C:\Users\Lalith\anaconda3\Lib\site-packages (from ragas) (1.4.4)
Requirement already satisfied: diskcache>=5.6.3 in C:\Users\Lalith\anaconda3\Lib\site-packages (from ragas) (5.6.3)
Requirement already satisfied: instructor in C:\Users\Lalith\anaconda3\Lib\site-packages (from ragas) (1.17.0)
Requirement already satisfied: pillow>=10.4.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from ragas) (11.1.0)
Requirement already satisfied: networkx in C:\Users\Lalith\anaconda3\Lib\site-packages (from ragas) (3.4.2)
Requirement already satisfied: scikit-network in C:\Users\Lalith\anaconda3\Lib\site-packages (from ragas) (0.33.5)
Requirement already satisfied: langchain in C:\Users\Lalith\anaconda3\Lib\site-packages (from ragas) (1.3.2)
Requirement already satisfied: langchain-core in C:\Users\Lalith\anaconda3\Lib\site-packages (from ragas) (1.6.3)
Requirement already satisfied: langchain-community in C:\Users\Lalith\anaconda3\Lib\site-packages (from ragas) (0.4.2)
Requirement already satisfied: langchain_openai in C:\Users\Lalith\anaconda3\Lib\site-packages (from ragas) (1.2.2)
Requirement already satisfied: pyarrow>=21.0.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from datasets) (25.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: requests>=2.32.2 in C:\Users\Lalith\anaconda3\Lib\site-packages (from datasets) (2.34.2)
Requirement already satisfied: xxhash in C:\Users\Lalith\anaconda3\Lib\site-packages (from datasets) (3.7.0)
Requirement already satisfied: multiprocess<0.70.20 in C:\Users\Lalith\anaconda3\Lib\site-packages (from datasets) (0.70.19)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in C:\Users\Lalith\anaconda3\Lib\site-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (3.14.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Lalith\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\Lalith\anaconda3\Lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\Lalith\anaconda3\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in C:\Users\Lalith\anaconda3\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in C:\Users\Lalith\anaconda3\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.18.0)
Requirement already satisfied: colorama in C:\Users\Lalith\anaconda3\Lib\site-packages (from click>=8.4.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.4.6)
Requirement already satisfied: six>=1.5 in C:\Users\Lalith\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Lalith\anaconda3\Lib\site-packages (from requests>=2.32.2->datasets) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\Lalith\anaconda3\Lib\site-packages (from requests>=2.32.2->datasets) (2.7.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in C:\Users\Lalith\anaconda3\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.1.0)
Requirement already satisfied: joblib>=1.2.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers) (3.5.0)
Requirement already satisfied: setuptools>=77.0.3 in C:\Users\Lalith\anaconda3\Lib\site-packages (from torch>=2.2->sentence-transformers) (84.0.0)
Requirement already satisfied: sympy>=1.13.3 in C:\Users\Lalith\anaconda3\Lib\site-packages (from torch>=2.2->sentence-transformers) (1.13.3)
Requirement already satisfied: jinja2 in C:\Users\Lalith\anaconda3\Lib\site-packages (from torch>=2.2->sentence-transformers) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from sympy>=1.13.3->torch>=2.2->sentence-transformers) (1.3.0)
Requirement already satisfied: docstring-parser<1.0,>=0.16 in C:\Users\Lalith\anaconda3\Lib\site-packages (from instructor->ragas) (0.18.0)
Requirement already satisfied: tenacity<10.0.0,>=8.2.3 in C:\Users\Lalith\anaconda3\Lib\site-packages (from instructor->ragas) (9.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from jinja2->torch>=2.2->sentence-transformers) (3.0.2)
Requirement already satisfied: langgraph<1.3.0,>=1.2.2 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langchain->ragas) (1.2.2)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langchain-core->ragas) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langchain-core->ragas) (0.0.19)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langchain-core->ragas) (0.8.7)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langchain-core->ragas) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in C:\Users\Lalith\anaconda3\Lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core->ragas) (2.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langgraph<1.3.0,>=1.2.2->langchain->ragas) (4.1.1)
Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langgraph<1.3.0,>=1.2.2->langchain->ragas) (1.1.0)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langgraph<1.3.0,>=1.2.2->langchain->ragas) (0.3.15)
Requirement already satisfied: ormsgpack>=1.12.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.2->langchain->ragas) (1.12.2)
Requirement already satisfied: orjson>=3.11.5 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain->ragas) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->ragas) (1.0.0)
Requirement already satisfied: websockets>=15.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->ragas) (16.0)
Requirement already satisfied: zstandard>=0.23.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->ragas) (0.23.0)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langchain-community->ragas) (0.4.3)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.7 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langchain-community->ragas) (1.0.8)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langchain-community->ragas) (2.15.0)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langchain-community->ragas) (2.0.39)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.2 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langchain-classic<2.0.0,>=1.0.7->langchain-community->ragas) (1.1.2)
Requirement already satisfied: typing-inspection>=0.4.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community->ragas) (0.4.2)
Requirement already satisfied: greenlet!=0.4.17 in C:\Users\Lalith\anaconda3\Lib\site-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain-community->ragas) (3.1.1)
Note: you may need to restart the kernel to use updated packages.

In [6]:
from dotenv import load_dotenv
load_dotenv()

True

In [7]:
from dotenv import load_dotenv
import os

load_dotenv()

print("API key loaded:", bool(os.getenv("OPENAI_API_KEY")))
print("Model:", os.getenv("OPENAI_MODEL"))

API key loaded: True
Model: gpt-5-nano

In [8]:
from chunking import chunk_folder

chunks = chunk_folder(
    "data/documents",
    chunk_size=1000,
    overlap=150
)

print("Number of chunks:", len(chunks))

Number of chunks: 1

In [9]:
for chunk in chunks[:3]:
    print("=" * 80)
    print("ID:", chunk["chunk_id"])
    print("Source:", chunk["source_doc"])
    print("Characters:", chunk["char_start"], "-", chunk["char_end"])
    print(chunk["text"][:500])

================================================================================
ID: sample_0
Source: sample.txt
Characters: 0 - 221
Company FAQ

Refunds are available within 30 days of purchase.
Standard shipping takes 3 to 5 business days.
Express shipping takes 1 to 2 business days.
Customer support is available Monday through Friday, 9 AM to 6 PM.

In [10]:
import pandas as pd

chunks_df = pd.DataFrame(chunks)

chunks_df.head(10)

,chunk_id,text,source_doc,char_start,char_end
0,sample_0,Company FAQ\n\nRefunds are available within 30...,sample.txt,0,221

In [11]:
from dense_retrieval import DenseRetriever

dense_retriever = DenseRetriever(chunks)

print("Dense retriever initialized.")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Dense retriever initialized.

In [12]:
query = "What is this document about?"

dense_results = dense_retriever.search(
    query,
    top_k=5
)

for result in dense_results:
    print("=" * 80)
    print("Chunk:", result["chunk_id"])
    print("Score:", result["score"])
    print(result["text"][:500])

================================================================================
Chunk: sample_0
Score: 0.03433665633201599
Company FAQ

Refunds are available within 30 days of purchase.
Standard shipping takes 3 to 5 business days.
Express shipping takes 1 to 2 business days.
Customer support is available Monday through Friday, 9 AM to 6 PM.

In [13]:
from bm25_retrieval import BM25Retriever

bm25_retriever = BM25Retriever(chunks)

bm25_results = bm25_retriever.search(
    query,
    top_k=5
)

for result in bm25_results:
    print("=" * 80)
    print("Chunk:", result["chunk_id"])
    print("Score:", result["score"])
    print(result["text"][:500])

================================================================================
Chunk: sample_0
Score: -0.2746530721670275
Company FAQ

Refunds are available within 30 days of purchase.
Standard shipping takes 3 to 5 business days.
Express shipping takes 1 to 2 business days.
Customer support is available Monday through Friday, 9 AM to 6 PM.

In [13]:
print("DENSE RESULTS")
for i, r in enumerate(dense_results, 1):
    print(i, r["chunk_id"], round(r["score"], 4))

print("\nBM25 RESULTS")
for i, r in enumerate(bm25_results, 1):
    print(i, r["chunk_id"], round(r["score"], 4))

DENSE RESULTS
1 sample_0 0.0343

BM25 RESULTS
1 sample_0 -0.2747

In [14]:
from hybrid_fusion import reciprocal_rank_fusion

rrf_results = reciprocal_rank_fusion(
    dense_results,
    bm25_results,
    k=60,
    top_k=10
)

for i, result in enumerate(rrf_results, 1):
    print(
        i,
        result["chunk_id"],
        round(result["score"], 4)
    )

1 sample_0 0.0343

In [15]:
from cross_encoder_reranking import CrossEncoderReranker

reranker = CrossEncoderReranker()

reranked_results = reranker.rerank(
    query,
    rrf_results,
    top_k=3
)

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

In [16]:
from generation import generate_answer

answer_result = generate_answer(
    query,
    reranked_results
)

print(answer_result["answer"])

It's a Company FAQ. [sample_0]

It includes information on refunds within 30 days of purchase. [sample_0]

It lists shipping times (standard 3 to 5 business days; express 1 to 2 business days). [sample_0]

It provides customer support hours (Monday through Friday, 9 AM to 6 PM). [sample_0]

In [17]:
from eval_dataset import generate_eval_dataset
import json
from pathlib import Path

eval_data = generate_eval_dataset(
    chunks,
    num_questions=20
)

print("Number of evaluation questions:", len(eval_data))

for item in eval_data[:3]:
    print("\n" + "=" * 80)
    print("Question:", item["question"])
    print("Ground truth:", item["ground_truth"])
    print("Context:", item["ground_truth_context"])

Number of evaluation questions: 20

================================================================================
Question: What is the refunds policy timeframe?
Ground truth: Refunds are available within 30 days of purchase.
Context: ['sample_0']

================================================================================
Question: How long does standard shipping take according to the document?
Ground truth: Standard shipping takes 3 to 5 business days.
Context: ['sample_0']

================================================================================
Question: What is the delivery timeframe for express shipping?
Ground truth: Express shipping takes 1 to 2 business days.
Context: ['sample_0']

In [18]:
eval_path = Path("data/eval_dataset.json")
eval_path.parent.mkdir(parents=True, exist_ok=True)

with open(eval_path, "w", encoding="utf-8") as f:
    json.dump(eval_data, f, indent=2, ensure_ascii=False)

print(f"Saved to: {eval_path}")

Saved to: data\eval_dataset.json

In [19]:
import pandas as pd

eval_df = pd.DataFrame(eval_data)
eval_df

,question,ground_truth,ground_truth_context
0,What is the refunds policy timeframe?,Refunds are available within 30 days of purchase.,[sample_0]
1,How long does standard shipping take according...,Standard shipping takes 3 to 5 business days.,[sample_0]
2,What is the delivery timeframe for express shi...,Express shipping takes 1 to 2 business days.,[sample_0]
3,When is customer support available?,Customer support is available Monday through F...,[sample_0]
4,On which days can you reach customer support?,Customer support is available Monday through F...,[sample_0]
5,What are the hours of operation for customer s...,Customer support is available Monday through F...,[sample_0]
6,Which sentence describes refunds within a cert...,Refunds are available within 30 days of purchase.,[sample_0]
7,How many business days are needed for standard...,Standard shipping takes 3 to 5 business days.,[sample_0]
8,What is the timeframe for express shipping?,Express shipping takes 1 to 2 business days.,[sample_0]
9,"If you need support, which days should you con...",Customer support is available Monday through F...,[sample_0]
10,"Which shipping option takes longer, standard o...",Standard shipping takes 3 to 5 business days.,[sample_0]
11,Which shipping option has a 1 to 2 day window?,Express shipping takes 1 to 2 business days.,[sample_0]
12,Which policy allows refunds within 30 days?,Refunds are available within 30 days of purchase.,[sample_0]
13,What is the shipping timeframe for standard sh...,Standard shipping takes 3 to 5 business days.,[sample_0]
14,What is the shipping timeframe for express shi...,Express shipping takes 1 to 2 business days.,[sample_0]
15,What are the customer support hours listed in ...,Customer support is available Monday through F...,[sample_0]
16,Which sentence mentions refunds?,Refunds are available within 30 days of purchase.,[sample_0]
17,Which sentence mentions express shipping durat...,Express shipping takes 1 to 2 business days.,[sample_0]
18,Which sentence mentions standard shipping dura...,Standard shipping takes 3 to 5 business days.,[sample_0]
19,What is the time range for customer support?,Customer support is available Monday through F...,[sample_0]

In [20]:
from rag_pipeline import RAGPipeline

pipeline = RAGPipeline(chunks)

print("Pipeline ready.")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

Pipeline ready.

In [2]:
%pip install -U langchain-openai

Requirement already satisfied: langchain-openai in C:\Users\Lalith\anaconda3\Lib\site-packages (1.2.2)
Collecting langchain-openai
  Downloading langchain_openai-1.6.2-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: certifi>=2024.6.2 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langchain-openai) (2025.4.26)
Requirement already satisfied: langchain-core<2.0.0,>=1.6.2 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langchain-openai) (1.6.3)
Collecting openai<4.0.0,>=2.45.0 (from langchain-openai)
  Downloading openai-3.13.0-py3-none-any.whl.metadata (41 kB)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langchain-openai) (0.13.0)
Requirement already satisfied: httpx<1.0.0,>=0.23.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.6.2->langchain-openai) (0.28.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.6.2->langchain-openai) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.6.2->langchain-openai) (0.0.19)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.6.2->langchain-openai) (0.8.7)
Requirement already satisfied: packaging>=23.2.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.6.2->langchain-openai) (24.2)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.6.2->langchain-openai) (2.10.3)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.6.2->langchain-openai) (6.0.2)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.6.2->langchain-openai) (9.0.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.6.2->langchain-openai) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.6.2->langchain-openai) (0.16.0)
Requirement already satisfied: anyio in C:\Users\Lalith\anaconda3\Lib\site-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.6.2->langchain-openai) (4.7.0)
Requirement already satisfied: httpcore==1.* in C:\Users\Lalith\anaconda3\Lib\site-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.6.2->langchain-openai) (1.0.9)
Requirement already satisfied: idna in C:\Users\Lalith\anaconda3\Lib\site-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.6.2->langchain-openai) (3.19)
Requirement already satisfied: h11>=0.16 in C:\Users\Lalith\anaconda3\Lib\site-packages (from httpcore==1.*->httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.6.2->langchain-openai) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in C:\Users\Lalith\anaconda3\Lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.6.2->langchain-openai) (2.1)
Requirement already satisfied: orjson>=3.9.14 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.2->langchain-openai) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.2->langchain-openai) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.2->langchain-openai) (2.34.2)
Requirement already satisfied: websockets>=15.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.2->langchain-openai) (16.0)
Requirement already satisfied: xxhash>=3.0.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.2->langchain-openai) (3.7.0)
Requirement already satisfied: zstandard>=0.23.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.2->langchain-openai) (0.23.0)
Collecting anyio (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.6.2->langchain-openai)
  Downloading anyio-4.15.1-py3-none-any.whl.metadata (4.7 kB)
Collecting httpx2<3,>=2.7.0 (from openai<4.0.0,>=2.45.0->langchain-openai)
  Downloading httpx2-2.12.0-py3-none-any.whl.metadata (9.5 kB)
Collecting jiter<1,>=0.16.0 (from openai<4.0.0,>=2.45.0->langchain-openai)
  Using cached jiter-0.16.0-cp313-cp313-win_amd64.whl.metadata (5.3 kB)
Requirement already satisfied: sniffio in C:\Users\Lalith\anaconda3\Lib\site-packages (from openai<4.0.0,>=2.45.0->langchain-openai) (1.3.0)
Collecting typing-extensions<5.0.0,>=4.7.0 (from langchain-core<2.0.0,>=1.6.2->langchain-openai)
  Using cached typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Collecting httpcore2==2.12.0 (from httpx2<3,>=2.7.0->openai<4.0.0,>=2.45.0->langchain-openai)
  Downloading httpcore2-2.12.0-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: truststore>=0.10 in C:\Users\Lalith\anaconda3\Lib\site-packages (from httpx2<3,>=2.7.0->openai<4.0.0,>=2.45.0->langchain-openai) (0.10.0)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.6.2->langchain-openai) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in C:\Users\Lalith\anaconda3\Lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.6.2->langchain-openai) (2.27.1)
Requirement already satisfied: regex in C:\Users\Lalith\anaconda3\Lib\site-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai) (2026.9.10)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Lalith\anaconda3\Lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.2->langchain-openai) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\Lalith\anaconda3\Lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.2->langchain-openai) (2.7.0)
Downloading langchain_openai-1.6.2-py3-none-any.whl (125 kB)
Downloading openai-3.13.0-py3-none-any.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 2.0/2.0 MB 32.7 MB/s  0:00:00
Downloading anyio-4.15.1-py3-none-any.whl (132 kB)
Downloading httpx2-2.12.0-py3-none-any.whl (95 kB)
Downloading httpcore2-2.12.0-py3-none-any.whl (83 kB)
Using cached jiter-0.16.0-cp313-cp313-win_amd64.whl (196 kB)
Using cached typing_extensions-4.16.0-py3-none-any.whl (45 kB)
Installing collected packages: typing-extensions, jiter, httpcore2, anyio, httpx2, openai, langchain-openai

  Attempting uninstall: typing-extensions

    Found existing installation: typing_extensions 4.15.0

    Uninstalling typing_extensions-4.15.0:

   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
      Successfully uninstalled typing_extensions-4.15.0
   ---------------------------------------- 0/7 [typing-extensions]
   ---------------------------------------- 0/7 [typing-extensions]
  Attempting uninstall: jiter
   ---------------------------------------- 0/7 [typing-extensions]
    Found existing installation: jiter 0.14.0
   ---------------------------------------- 0/7 [typing-extensions]
    Uninstalling jiter-0.14.0:
   ---------------------------------------- 0/7 [typing-extensions]
      Successfully uninstalled jiter-0.14.0
   ---------------------------------------- 0/7 [typing-extensions]
   ----------- ---------------------------- 2/7 [httpcore2]
   ----------- ---------------------------- 2/7 [httpcore2]
   ----------- ---------------------------- 2/7 [httpcore2]
  Attempting uninstall: anyio
   ----------- ---------------------------- 2/7 [httpcore2]
    Found existing installation: anyio 4.7.0
   ----------- ---------------------------- 2/7 [httpcore2]
    Uninstalling anyio-4.7.0:
   ----------- ---------------------------- 2/7 [httpcore2]
   ----------------- ---------------------- 3/7 [anyio]
      Successfully uninstalled anyio-4.7.0
   ----------------- ---------------------- 3/7 [anyio]
   ----------------- ---------------------- 3/7 [anyio]
   ----------------- ---------------------- 3/7 [anyio]
   ----------------- ---------------------- 3/7 [anyio]
   ----------------- ---------------------- 3/7 [anyio]
   ----------------- ---------------------- 3/7 [anyio]
   ---------------------- ----------------- 4/7 [httpx2]
   ---------------------- ----------------- 4/7 [httpx2]
   ---------------------- ----------------- 4/7 [httpx2]
  Attempting uninstall: openai
   ---------------------- ----------------- 4/7 [httpx2]
    Found existing installation: openai 2.38.0
   ---------------------- ----------------- 4/7 [httpx2]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
    Uninstalling openai-2.38.0:
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
      Successfully uninstalled openai-2.38.0
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]
   ---------------------------- ----------- 5/7 [openai]

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
instructor 1.17.0 requires jiter<0.15,>=0.6.1, but you have jiter 0.16.0 which is incompatible.

In [3]:
from ragas.llms import llm_factory
from ragas.embeddings import OpenAIEmbeddings
from ragas.metrics.collections import (
    Faithfulness,
    AnswerRelevancy,
    ContextPrecision,
    ContextRecall,
    AnswerCorrectness,
)

print("RAGAS evaluation components loaded successfully.")

RAGAS evaluation components loaded successfully.

In [22]:
from hybrid_fusion import weighted_score_fusion

weighted_results = weighted_score_fusion(
    dense_results,
    bm25_results,
    beta=0.5,
    top_k=10
)

print("Weighted fusion results:")

for i, result in enumerate(weighted_results, 1):
    print(
        f"{i}. {result['chunk_id']} "
        f"score={result['score']:.4f}"
    )

Weighted fusion results:
1. sample_0 score=-0.2747

In [23]:
test_query = "What is the standard shipping timeframe?"

strategies = [
    "bm25",
    "dense",
    "hybrid_rrf",
    "hybrid_reranked"
]

for strategy in strategies:
    print("\n" + "=" * 80)
    print("STRATEGY:", strategy)

    result = pipeline.answer(
        test_query,
        strategy=strategy
    )

    print("\nANSWER:")
    print(result["answer"])

    print("\nRETRIEVED CHUNKS:")
    print([
        chunk["chunk_id"]
        for chunk in result["retrieved_chunks"]
    ])

================================================================================
STRATEGY: bm25

ANSWER:
Standard shipping takes 3 to 5 business days. [sample_0]

RETRIEVED CHUNKS:
['sample_0']

================================================================================
STRATEGY: dense

ANSWER:
Standard shipping takes 3 to 5 business days. [sample_0]

RETRIEVED CHUNKS:
['sample_0']

================================================================================
STRATEGY: hybrid_rrf

ANSWER:
Standard shipping takes 3 to 5 business days. [sample_0]

RETRIEVED CHUNKS:
['sample_0']

================================================================================
STRATEGY: hybrid_reranked

ANSWER:
Standard shipping takes 3 to 5 business days. [sample_0]

RETRIEVED CHUNKS:
['sample_0']

In [24]:
test_questions = [
    "What is the standard shipping timeframe?",
    "How long does express shipping take?",
    "What is the refund window?",
    "When can I contact customer support?"
]

for question in test_questions:

    print("\n" + "=" * 80)
    print("QUESTION:", question)

    result = pipeline.answer(
        question,
        strategy="hybrid_reranked"
    )

    print("\nANSWER:")
    print(result["answer"])

    print("\nSOURCES:")
    for chunk in result["retrieved_chunks"]:
        print("-", chunk["chunk_id"])

================================================================================
QUESTION: What is the standard shipping timeframe?

ANSWER:
Standard shipping takes 3 to 5 business days. [sample_0]

SOURCES:
- sample_0

================================================================================
QUESTION: How long does express shipping take?

ANSWER:
Express shipping takes 1 to 2 business days. [sample_0]

SOURCES:
- sample_0

================================================================================
QUESTION: What is the refund window?

ANSWER:
Refunds are available within 30 days of purchase. [sample_0]

SOURCES:
- sample_0

================================================================================
QUESTION: When can I contact customer support?

ANSWER:
Customer support is available Monday through Friday, 9 AM to 6 PM. [sample_0]

SOURCES:
- sample_0

In [25]:
comparison_query = "What is the standard shipping timeframe?"

dense = dense_retriever.search(
    comparison_query,
    top_k=5
)

bm25 = bm25_retriever.search(
    comparison_query,
    top_k=5
)

rrf = reciprocal_rank_fusion(
    dense,
    bm25,
    k=60,
    top_k=10
)

reranked = reranker.rerank(
    comparison_query,
    rrf,
    top_k=3
)

In [26]:
import pandas as pd

retrieval_comparison = pd.DataFrame({
    "Dense": [x["chunk_id"] for x in dense],
    "BM25": [x["chunk_id"] for x in bm25],
})

retrieval_comparison

      Dense      BM25
0  sample_0  sample_0

In [27]:
pd.DataFrame([
    {
        "rank": i + 1,
        "chunk_id": x["chunk_id"],
        "rerank_score": x["rerank_score"]
    }
    for i, x in enumerate(reranked)
])

   rank  chunk_id  rerank_score
0     1  sample_0       3.48275

In [28]:
%pip install streamlit

Requirement already satisfied: streamlit in C:\Users\Lalith\anaconda3\Lib\site-packages (1.45.1)
Requirement already satisfied: altair<6,>=4.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<6,>=4.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from streamlit) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from streamlit) (8.4.1)
Requirement already satisfied: numpy<3,>=1.23 in C:\Users\Lalith\anaconda3\Lib\site-packages (from streamlit) (2.1.3)
Requirement already satisfied: packaging<25,>=20 in C:\Users\Lalith\anaconda3\Lib\site-packages (from streamlit) (24.2)
Requirement already satisfied: pandas<3,>=1.4.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from streamlit) (2.2.3)
Requirement already satisfied: pillow<12,>=7.1.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from streamlit) (11.1.0)
Requirement already satisfied: protobuf<7,>=3.20 in C:\Users\Lalith\anaconda3\Lib\site-packages (from streamlit) (5.29.3)
Requirement already satisfied: pyarrow>=7.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from streamlit) (25.0.1)
Requirement already satisfied: requests<3,>=2.27 in C:\Users\Lalith\anaconda3\Lib\site-packages (from streamlit) (2.34.2)
Requirement already satisfied: tenacity<10,>=8.1.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from streamlit) (9.0.0)
Requirement already satisfied: toml<2,>=0.10.1 in C:\Users\Lalith\anaconda3\Lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from streamlit) (4.16.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in C:\Users\Lalith\anaconda3\Lib\site-packages (from streamlit) (4.0.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in C:\Users\Lalith\anaconda3\Lib\site-packages (from streamlit) (3.1.43)
Requirement already satisfied: tornado<7,>=6.0.3 in C:\Users\Lalith\anaconda3\Lib\site-packages (from streamlit) (6.5.1)
Requirement already satisfied: jinja2 in C:\Users\Lalith\anaconda3\Lib\site-packages (from altair<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: narwhals>=1.14.2 in C:\Users\Lalith\anaconda3\Lib\site-packages (from altair<6,>=4.0->streamlit) (1.31.0)
Requirement already satisfied: colorama in C:\Users\Lalith\anaconda3\Lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in C:\Users\Lalith\anaconda3\Lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)
Requirement already satisfied: smmap<5,>=3.0.1 in C:\Users\Lalith\anaconda3\Lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Lalith\anaconda3\Lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\Lalith\anaconda3\Lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\Lalith\anaconda3\Lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Lalith\anaconda3\Lib\site-packages (from requests<3,>=2.27->streamlit) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\Lalith\anaconda3\Lib\site-packages (from requests<3,>=2.27->streamlit) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\Lalith\anaconda3\Lib\site-packages (from requests<3,>=2.27->streamlit) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\Lalith\anaconda3\Lib\site-packages (from requests<3,>=2.27->streamlit) (2025.4.26)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (24.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\Lalith\anaconda3\Lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\Lalith\anaconda3\Lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in C:\Users\Lalith\anaconda3\Lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.22.3)
Requirement already satisfied: six>=1.5 in C:\Users\Lalith\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\Lalith\anaconda3\Lib\site-packages (from jinja2->altair<6,>=4.0->streamlit) (3.0.2)
Note: you may need to restart the kernel to use updated packages.

In [29]:
import streamlit as st
from rag_pipeline import RAGPipeline
from chunking import chunk_folder


@st.cache_resource
def load_pipeline():
    chunks = chunk_folder(
        "data/documents",
        chunk_size=1000,
        overlap=150
    )

    return RAGPipeline(chunks)


pipeline = load_pipeline()

st.title("RAG Assistant")
st.caption("Hybrid retrieval + cross-encoder reranking")


if "messages" not in st.session_state:
    st.session_state.messages = []


for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])


if prompt := st.chat_input("Ask a question..."):

    st.session_state.messages.append({
        "role": "user",
        "content": prompt
    })

    with st.chat_message("user"):
        st.markdown(prompt)

    result = pipeline.answer(
        prompt,
        strategy="hybrid_reranked"
    )

    answer = result["answer"]

    with st.chat_message("assistant"):
        st.markdown(answer)

        with st.expander("Retrieved sources"):
            for chunk in result["retrieved_chunks"]:
                st.write(
                    f"**{chunk['chunk_id']}** — "
                    f"{chunk['source_doc']}"
                )
                st.write(chunk["text"])

    st.session_state.messages.append({
        "role": "assistant",
        "content": answer
    })

2026-09-12 19:18:04.265 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-12 19:18:04.642
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\Lalith\anaconda3\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-09-12 19:18:04.643 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-12 19:18:04.645 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-12 19:18:05.162 Thread 'Thread-10': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-12 19:18:05.167 Thread 'Thread-10': missing ScriptRunContext! This warning can be ignored when running in bare mode.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

2026-09-12 19:18:21.277 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-12 19:18:21.280 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-12 19:18:21.282 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-12 19:18:21.285 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-12 19:18:21.286 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-12 19:18:21.287 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-12 19:18:21.288 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-12 19:18:21.290 Session state does not function when running a script without `streamlit run`
2026-09-12 19:18:21.292 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-12 19:18:21.294 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-12 19:18:21.296 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-12 19:18:21.299 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-12 19:18:21.300 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-12 19:18:21.302 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-12 19:18:21.304 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-12 19:18:21.305 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.